### ISSUE TITLE
Hello, what did you do with a song? I'm a little confused after reading your code.

### ISSUE THREAD

**Issue by ymm-youbaba** [Aditya-Khadilkar/Music-Synth#3]

**Comment by Aditya-Khadilkar** [comment]
Made new songs?

**Comment by ymm-youbaba** [comment]
I didn't understand how you handled every note. Can you tell me how you handled the notes of a song and then did Markov transformation?

**Comment by Aditya-Khadilkar** [comment]
I used byte pair encoding to make groups of "frequently repeated notes". I then used Markov model on those groups.

**Comment by ymm-youbaba** [comment]
I haven't finished reading your code, but I can't understand it now. The music you make is really nice. I want to try to understand how you handle it.

**Comment by ymm-youbaba** [comment]
THANK YOU VERY MUCH!

**Comment by Aditya-Khadilkar** [comment]
Thanks! :)

**Comment by ymm-youbaba** [comment]
hellow.In the file "BPEdict.json", why do some keys correspond to two numbers and some keys correspond to three numbers?

**Comment by Aditya-Khadilkar** [comment]
Because the "frequently repeated pattern" happened to contain 3 notes.
It can have an arbitrary number of notes.

**Comment by Aditya-Khadilkar** [comment]
I'd recommend you look into what byte pair encoding is, you can understand what I've done if you know byte pair encoding is

**Comment by ymm-youbaba** [comment]
Thank you. I'm going to study now.

**Comment by ymm-youbaba** [comment]
Hello, excuse me, why is -3 changed to 19 and 0 here?
![NY7GU~4)6`%Y@NMF`VDS6P3](https://user-images.githubusercontent.com/75113940/145384271-ff2351cc-83e7-477d-8201-56174db43a38.png)

**Comment by ymm-youbaba** [comment]
Hello, why do you want to change -3 to the third element [19,0] in valist here?
![LI 6A$SV 8FERFX}_GA8%B](https://user-images.githubusercontent.com/75113940/145385829-aca11598-804f-4a12-833f-dc12c7886c97.png)
